prettier

diff --git a/.github/workflows/Super-linter.yaml b/.github/workflows/Super-linter.yaml
--- a/.github/workflows/Super-linter.yaml
+++ b/.github/workflows/Super-linter.yaml
@@ -1,33 +1,37 @@
 ---
-name: Lint
+name: Lint commit
 
-on: # yamllint disable-line rule:truthy
-  push: null
-  pull_request: null
+on:
+  push:
+  pull_request:
+  merge_group:
 
+# Don't grant any access by default
 permissions: {}
 
 jobs:
-  build: 
-    name: Lint
+  commitlint:
     runs-on: ubuntu-latest
-
     permissions:
       contents: read
-      packages: read
-      # To report GitHub Actions status checks
-      statuses: write
-
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
+      - uses: actions/checkout@v4
         with:
-          # super-linter needs the full git history to get the
-          # list of files that changed across commits
           fetch-depth: 0
 
-      - name: Super-linter
-        uses: super-linter/super-linter@v7.3.0 # x-release-please-version
-        env:
-          # To report GitHub Actions status checks
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      - name: Check if the pull request contains a single commit
+        if: github.event_name == 'pull_request'
+        run: |
+          commit_count=${{ github.event.pull_request.commits }}
+
+          if [ -z ${commit_count} ]; then
+            echo "[ERROR] commit_count is empty"
+            exit 1
+          fi
+
+          if [[ ${commit_count} -ne 1 ]]; then
+            echo "[ERROR] This pull request contains ${commit_count} commits. Squash these commits into a single commit."
+            exit 1
+          else
+            echo "This pull request contains ${commit_count} commit."
+          fi
